import test from 'node:test';import assert from 'node:assert/strict';
import {board} from '../src/physics';
import {HARVEST_ITEMS,HAZARD_PROBABILITY,chooseItem,makeFruit,harvestStep} from '../src/harvest';
import {gameDuration,loadColors,DEFAULT_COLORS,labelColor} from '../src/settings';
test('duration is integral, bounded 10–60, and defaults to 30',()=>{for(let n=10;n<=60;n++)assert.equal(gameDuration(n),n);assert.equal(gameDuration(9),10);assert.equal(gameDuration(90),60);assert.equal(gameDuration(24.7),25);assert.equal(gameDuration(NaN),30);});
test('colors restore independently and invalid storage remains safe',()=>{assert.deepEqual(loadColors({getItem:()=>JSON.stringify({p1:'#ff0000',p2:'#00ff00',puck:'#ffffff'})}),{p1:'#ff0000',p2:'#00ff00',puck:'#ffffff'});assert.deepEqual(loadColors({getItem:()=>'{broken'}),DEFAULT_COLORS);assert.equal(loadColors({getItem:()=>'{"p1":"bad"}'}).p1,DEFAULT_COLORS.p1);assert.equal(labelColor('#ffffff'),'#172b3a');assert.equal(labelColor('#000000'),'#ffffff');});
test('all eight normal items spawn, hazards only on hard at configured threshold',()=>{assert.equal(HAZARD_PROBABILITY,.25);for(const difficulty of [0,1]){const seen=new Set<number>();for(let i=0;i<800;i++){const kind=chooseItem(difficulty,()=>i/800);assert.equal(HARVEST_ITEMS[kind].hazard,false);seen.add(kind);}assert.equal(seen.size,8);}for(let i=0;i<3;i++){let calls=0;const kind=chooseItem(2,()=>calls++===0?.249:(i+.1)/3);assert.equal(HARVEST_ITEMS[kind].id,['mushroom','spider','snake'][i]);}let calls=0;assert.equal(HARVEST_ITEMS[chooseItem(2,()=>calls++===0?.25:0)].hazard,false);});
test('every normal item uses its radius/speed and scores only once after one second',()=>{const b=board({x:0,y:0},{x:0,y:0},350,.44);for(let kind=0;kind<8;kind++){const item=HARVEST_ITEMS[kind],f=makeFruit(kind,500);assert.equal(f.r,item.radius);assert.equal(f.vy,item.speed);f.y=b.y-f.r-1;harvestStep(f,b,.1,1);assert.equal(f.caught,true);assert.equal(f.done,false);let sum=0;for(let i=0;i<500;i++)sum+=harvestStep(f,b,1/240,1);assert.equal(sum,item.points);}});
test('each hazard penalizes once on contact, disappears, and misses cost nothing',()=>{const b=board({x:0,y:0},{x:0,y:0},350,.44);for(let kind=8;kind<11;kind++){const f=makeFruit(kind,500);f.y=b.y-f.r-1;assert.equal(harvestStep(f,b,.1,1),HARVEST_ITEMS[kind].points);assert.equal(f.done,true);assert.equal(harvestStep(f,b,.1,1),0);const miss=makeFruit(kind,100);let sum=0;for(let i=0;i<2000;i++)sum+=harvestStep(miss,b,1/240,1);assert.equal(sum,0);assert.equal(miss.done,true);}});
