import {test,expect} from '@playwright/test';
test('independent palette/custom colors persist and render on SVG and Canvas',async({page})=>{
 await page.goto('./');await expect(page.locator('#hockey svg')).toHaveAttribute('aria-label','上から見たエアホッケー台');await expect(page.locator('#hockey')).not.toContainText('🏑');
 await page.locator('#hockey').click();
 for(const key of ['p1','p2','puck'])await expect(page.locator(`.swatch[data-target=${key}]`)).toHaveCount(9);
 await page.locator('.swatch[data-target=p1][aria-label="緑"]').click();await page.locator('.swatch[data-target=p2][aria-label="ピンク"]').click();await page.locator('#color-puck').fill('#abcdef');
 await expect(page.locator('[data-icon-color=p1]')).toHaveAttribute('fill','#3b945b');await expect(page.locator('[data-icon-color=p2]')).toHaveAttribute('fill','#ed83b2');await expect(page.locator('[data-icon-color=puck]')).toHaveAttribute('fill','#abcdef');
 await page.reload();await page.locator('#hockey').click();await expect(page.locator('#color-p1')).toHaveValue('#3b945b');await expect(page.locator('#color-p2')).toHaveValue('#ed83b2');await expect(page.locator('#color-puck')).toHaveValue('#abcdef');
 await page.locator('#demo').check();await page.locator('#start').click();await page.waitForTimeout(3200);
 const counts=await page.locator('#game').evaluate((element)=>{const canvas=element as HTMLCanvasElement,data=canvas.getContext('2d')!.getImageData(0,0,1000,700).data;const colors=[[59,148,91],[237,131,178],[171,205,239]];return colors.map(color=>{let n=0;for(let i=0;i<data.length;i+=4)if(color.every((v,k)=>data[i+k]===v))n++;return n;});});expect(counts.every(n=>n>50)).toBe(true);
 await page.locator('#home').click();await page.locator('#hockey').click();for(const key of ['p1','p2','puck'])await page.locator(`#color-${key}`).fill('#abcdef');await expect(page.locator('#color-warning')).toBeVisible();
});
for(const game of ['harvest','hockey'])for(const seconds of [10,30,60])test(`${game} ends at ${seconds}s, pauses and restarts`,async({page})=>{
 await page.clock.install();await page.goto('./');await page.locator('#'+game).click();await expect(page.locator('#duration')).toHaveAttribute('min','10');await expect(page.locator('#duration')).toHaveAttribute('max','60');await expect(page.locator('#duration')).toHaveAttribute('step','1');await expect(page.locator('#duration')).toHaveValue('30');
 await page.locator('#duration').fill(String(seconds));await expect(page.locator('#duration-value')).toHaveText(`${seconds} 秒`);await page.locator('#demo').check();await page.locator('#start').click();await page.clock.runFor(3100);await expect(page.locator('#game')).toHaveAttribute('data-state','running');
 await page.locator('#pause').click();const before=await page.locator('#time-status').textContent();await page.clock.fastForward(20000);await expect(page.locator('#time-status')).toHaveText(before!);await page.locator('#pause').click();await page.clock.runFor(3100);
 await page.locator('#restart').click();await page.clock.runFor(16);await expect(page.locator('#time-status')).toHaveText(`残り ${seconds} 秒`);await expect(page.locator('#game')).toHaveAttribute('data-state','countdown');
 await page.clock.runFor(3100);await page.clock.fastForward((seconds-1)*1000);await expect(page.locator('#game')).toHaveAttribute('data-state','running');await page.clock.fastForward(1000);await expect(page.locator('#game')).toHaveAttribute('data-state','ended');await expect(page.locator('#time-status')).toHaveText('残り 0 秒');await expect(page.locator('#result')).not.toBeEmpty();
});
test('hard harvest shows danger explanation and mute stays synchronized',async({page})=>{await page.goto('./');await page.locator('#harvest').click();await expect(page.locator('#harvest-help')).toContainText('ふたりで1枚のお盆');await expect(page.locator('#hazard-help')).toBeHidden();await page.locator('#difficulty').selectOption('2');await expect(page.locator('#hazard-help')).toHaveText('毒キノコや虫・ヘビには気をつけて！');await page.locator('#mute').check();await page.locator('#demo').check();await page.locator('#start').click();await expect(page.locator('#play-mute')).toBeChecked();await page.locator('#play-mute').uncheck();await page.locator('#home').click();await page.locator('#harvest').click();await expect(page.locator('#mute')).not.toBeChecked();});
