import Peer,{type DataConnection} from 'peerjs';
import QRCode from 'qrcode';
import {board,fruitStep,hockeyStep,clamp,type Point,type Fruit,type Puck} from './physics';
import './style.css';
const app=document.querySelector<HTMLDivElement>('#app')!;
const inputs:Point[]=[{x:0,y:0},{x:0,y:0}];
const query=new URLSearchParams(location.search),host=query.get('host'),slot=Number(query.get('player'));
const modes=['touch','touch'];const connected=[false,false];const lastInput=[0,0];let peer:Peer|undefined,connections:(DataConnection|undefined)[]=[];
let audio:AudioContext|undefined;
function beep(freq=600){try{audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.16);}catch{}}
function button(id:string,fn:()=>void){document.getElementById(id)!.onclick=fn;}
function startPeer(){peer=new Peer(import.meta.env.VITE_PEER_HOST?{host:import.meta.env.VITE_PEER_HOST,port:Number(import.meta.env.VITE_PEER_PORT||9000),path:'/peerjs',secure:false}:{});peer.on('disconnected',()=>{if(!peer?.destroyed)peer?.reconnect();});peer.on('error',()=>{const el=document.getElementById('network');if(el)el.textContent='通信サービスに接続できません。再接続またはデモをお使いください。';});return peer;}
function controller(){
 app.innerHTML=`<main class="controller"><h1>プレイヤー ${slot+1}</h1><p id="network" role="status">接続しています…</p><div class="row"><button id="touch">指で操作</button><button id="tilt">傾き操作を許可</button><button id="zero">中央に戻す</button><button id="retry">再接続</button></div><label>感度 <input id="sensitivity" type="range" min="0.5" max="3" step="0.1" value="1"></label><p id="help">四角の中をドラッグして操作します</p><div id="pad"><span id="marker"></span></div></main>`;
 let conn:DataConnection|undefined,mode='touch',base:Point|undefined,latest:Point|undefined,pos:Point={x:0,y:0};
 const pad=document.getElementById('pad')!,marker=document.getElementById('marker')!,status=document.getElementById('network')!;
 function show(){marker.style.left=`${(pos.x+1)*50}%`;marker.style.top=`${(pos.y+1)*50}%`;}
 function connect(){if(!peer?.id)return;conn?.close();conn=peer.connect(host!,{reliable:true,metadata:{slot}});conn.on('open',()=>{status.textContent='接続しました';});conn.on('data',(d:unknown)=>{const m=d as {mode?:string};if(m.mode==='tilt')document.getElementById('help')!.textContent='傾き操作を許可ボタンを押してください';});conn.on('close',()=>{status.textContent='切断しました。再接続してください';});conn.on('error',()=>{status.textContent='通信エラー。再接続してください';});}
 const p=startPeer();p.on('open',connect);button('retry',()=>{if(p.disconnected)p.reconnect();connect();});
 function touch(e:PointerEvent){if(mode!=='touch')return;const r=pad.getBoundingClientRect();pos={x:clamp((e.clientX-r.left)/r.width*2-1,-1,1),y:clamp((e.clientY-r.top)/r.height*2-1,-1,1)};show();}
 pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);touch(e);};pad.onpointermove=e=>{if(pad.hasPointerCapture(e.pointerId))touch(e);};
 button('touch',()=>{mode='touch';document.getElementById('help')!.textContent='四角の中をドラッグして操作します';});
 button('zero',()=>{base=latest;pos={x:0,y:0};show();});
 button('tilt',async()=>{try{const sensor=DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<string>};if(sensor.requestPermission&&await sensor.requestPermission()!=='granted')throw Error();mode='tilt';lastSensor=performance.now();base=undefined;document.getElementById('help')!.textContent='端末を傾けて操作。現在の姿勢が中央になります';}catch{mode='touch';document.getElementById('help')!.textContent='傾きが使えません。指で操作してください';}});
 let lastSensor=performance.now();window.addEventListener('deviceorientation',e=>{if(e.gamma===null||e.beta===null)return;lastSensor=performance.now();latest={x:e.gamma,y:e.beta};if(mode!=='tilt')return;base??=latest;const s=Number((document.getElementById('sensitivity') as HTMLInputElement).value);pos.x+=.18*(clamp((latest.x-base.x)/25*s,-1,1)-pos.x);pos.y+=.18*(clamp((latest.y-base.y)/25*s,-1,1)-pos.y);show();});
 setInterval(()=>{if(conn?.open)conn.send({x:pos.x,y:pos.y});if(mode==='tilt'&&performance.now()-lastSensor>4000){mode='touch';document.getElementById('help')!.textContent='センサ入力がありません。指で操作に切り替えました';}},33);show();
}
let game='harvest',demo=false,duration=60,difficulty=1,maxAngle=25,state='idle',remaining=60,count=3,score=[0,0],fruits:Fruit[]=[],spawn=0,puck:Puck={x:500,y:350,vx:0,vy:240},serve=0;
let pads=[{x:500,y:550,vx:0,vy:0},{x:500,y:150,vx:0,vy:0}];let canvas:HTMLCanvasElement,ctx:CanvasRenderingContext2D;
const keys=new Set<string>();window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase());}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
function setupHost(){
 app.innerHTML=`<header><span>🍂 ふたりのゲーム広場</span><h1>ふたりであそぼう！</h1><p>協力したり、対戦したり。ふたりの動きでゲームが変わる！</p></header><main><section id="menu"><div class="cards"><button class="card" id="harvest">🌰<strong>秋の収穫</strong><small>ふたりで板を動かし、果物をキャッチ！</small></button><button class="card blue" id="hockey">🏑<strong>エアホッケー</strong><small>パックを相手のゴールへ！</small></button></div></section><section id="settings" hidden><h2 id="title"></h2><div class="row"><label>時間 <select id="duration"><option>30</option><option selected>60</option><option>90</option></select> 秒</label><label>難易度 <select id="difficulty"><option value="0">やさしい</option><option value="1" selected>ふつう</option><option value="2">むずかしい</option></select></label><label>最大傾斜 <input id="angle" type="number" min="5" max="45" value="25"> 度</label></div><div class="row"><label><input id="demo" type="checkbox"> キーボードデモ（スマホ不要）</label><button id="back">ゲーム選択へ</button></div><p id="network" role="status">通信サービスに接続しています…</p><div class="players">${[0,1].map(i=>`<article><h3>プレイヤー ${i+1}</h3><p id="status${i}">未接続</p><label>入力 <select id="mode${i}"><option value="touch">タッチ</option><option value="tilt">傾き</option></select></label><canvas id="qr${i}" class="qr"></canvas><a id="link${i}" target="_blank">コントローラーを開く</a></article>`).join('')}</div><p>デモ操作：P1＝WASD、P2＝矢印キー。秋の収穫は板を水平にして1秒保持。</p><button id="start" class="primary">START</button><p id="reason" role="status"></p></section><section id="play" hidden><div class="row controls"><button id="pause">PAUSE</button><button id="restart">RESTART</button><button id="home">HOME</button><button id="fullscreen">FULLSCREEN</button><span id="connection"></span></div><canvas id="game" width="1000" height="700" aria-label="ゲーム画面"></canvas><p id="result" role="status"></p></section></main><footer>ふたりのペースで、楽しくあそぼう。</footer>`;
 canvas=document.getElementById('game') as HTMLCanvasElement;ctx=canvas.getContext('2d')!;
 for(const kind of ['harvest','hockey'])button(kind,()=>{game=kind;document.getElementById('menu')!.hidden=true;document.getElementById('settings')!.hidden=false;document.getElementById('title')!.textContent=kind==='harvest'?'🍂 秋の収穫':'🏑 エアホッケー';});
 button('back',home);button('home',home);button('start',start);button('restart',start);button('pause',()=>{if(state==='running'||state==='countdown'){state='paused';}else if(state==='paused'){state='countdown';count=3;}document.getElementById('pause')!.textContent=state==='paused'?'RESUME':'PAUSE';});button('fullscreen',()=>{void document.documentElement.requestFullscreen?.().catch(()=>{});});
 (document.getElementById('demo') as HTMLInputElement).onchange=e=>{demo=(e.target as HTMLInputElement).checked;statuses();};
 for(let i=0;i<2;i++)(document.getElementById(`mode${i}`) as HTMLSelectElement).onchange=e=>{modes[i]=(e.target as HTMLSelectElement).value;connections[i]?.send({mode:modes[i]});};
 const p=startPeer();p.on('open',id=>{document.getElementById('network')!.textContent='QRをそれぞれ別のスマホで読み取ってください';for(let i=0;i<2;i++){const u=new URL(location.href);u.search='';u.searchParams.set('host',id);u.searchParams.set('player',String(i));void QRCode.toCanvas(document.getElementById(`qr${i}`),u.href,{width:190});(document.getElementById(`link${i}`) as HTMLAnchorElement).href=u.href;}});
 p.on('connection',conn=>{const i=conn.metadata?.slot;if(i!==0&&i!==1){conn.close();return;}connections[i]?.close();connections[i]=conn;conn.on('open',()=>{connected[i]=true;lastInput[i]=performance.now();conn.send({mode:modes[i]});statuses();});conn.on('data',(data:unknown)=>{const d=data as Point;if(Number.isFinite(d.x)&&Number.isFinite(d.y)){lastInput[i]=performance.now();if(!connected[i]){connected[i]=true;statuses();}inputs[i]={x:clamp(d.x,-1,1),y:clamp(d.y,-1,1)};}});const lost=()=>{if(connections[i]!==conn)return;connected[i]=false;statuses();if(!demo&&(state==='running'||state==='countdown')){state='paused';document.getElementById('pause')!.textContent='RESUME';}};conn.on('close',lost);conn.on('error',lost);});setInterval(()=>{for(let i=0;i<2;i++)if(connected[i]&&performance.now()-lastInput[i]>3000){connected[i]=false;statuses();if(!demo&&(state==='running'||state==='countdown')){state='paused';document.getElementById('pause')!.textContent='RESUME';}}},500);statuses();requestAnimationFrame(frame);
}
function statuses(){for(let i=0;i<2;i++)document.getElementById(`status${i}`)!.textContent=connected[i]?'● 接続済み':'○ 未接続';document.getElementById('reason')!.textContent=demo?'デモで開始できます':connected.every(Boolean)?'ふたりの準備ができました':'スマホ2台の接続が必要です';document.getElementById('connection')!.textContent=demo?'デモ':connected.map((v,i)=>`P${i+1} ${v?'接続済み':'未接続'}`).join(' / ');}
function home(){state='idle';document.getElementById('menu')!.hidden=false;document.getElementById('settings')!.hidden=true;document.getElementById('play')!.hidden=true;}
function start(){if(!demo&&!connected.every(Boolean)){statuses();return;}duration=Number((document.getElementById('duration') as HTMLSelectElement).value);difficulty=Number((document.getElementById('difficulty') as HTMLSelectElement).value);maxAngle=clamp(Number((document.getElementById('angle') as HTMLInputElement).value)||25,5,45);remaining=duration;count=3;score=[0,0];fruits=[];spawn=0;serve=0;puck={x:500,y:350,vx:80,vy:240};state='countdown';document.getElementById('settings')!.hidden=true;document.getElementById('play')!.hidden=false;document.getElementById('result')!.textContent='';document.getElementById('pause')!.textContent='PAUSE';beep();}
let last=0,acc=0;function frame(t:number){const dt=Math.min((t-last)/1000,.05);last=t;acc+=dt;while(acc>=1/240){tick(1/240);acc-=1/240;}draw();requestAnimationFrame(frame);}
function tick(dt:number){if(state==='idle'||state==='ended')return;if(demo){const sets=[['a','d','w','s'],['arrowleft','arrowright','arrowup','arrowdown']];sets.forEach((k,i)=>{inputs[i].x=clamp(inputs[i].x+(Number(keys.has(k[1]))-Number(keys.has(k[0])))*dt*1.2,-1,1);inputs[i].y=clamp(inputs[i].y+(Number(keys.has(k[3]))-Number(keys.has(k[2])))*dt*1.2,-1,1);});}
 if(state==='paused')return;if(!demo&&!connected.every(Boolean)){state='paused';return;}if(state==='countdown'){count-=dt;if(count<=0)state='running';return;}
 remaining-=dt;if(remaining<=0){remaining=0;state='ended';document.getElementById('result')!.textContent=game==='harvest'?`収穫できました！ ${score[0]} 点` :score[0]===score[1]?'引き分け！':`プレイヤー ${score[0]>score[1]?1:2} の勝ち！`;beep(900);return;}
 if(game==='harvest'){const length=[430,350,280][difficulty],b=board(inputs[0],inputs[1],length,maxAngle*Math.PI/180);spawn-=dt;if(spawn<=0){const kind=Math.floor(Math.random()*3);fruits.push({x:60+Math.random()*880,y:-30,r:19,vy:[115,95,130][kind],kind,s:0,v:0,held:0,caught:false,done:false});spawn=[2.3,1.7,1.1][difficulty];}for(const f of fruits)if(fruitStep(f,b,dt,[.75,1,1.5][difficulty])){score[0]+=[10,20,15][f.kind];beep();}fruits=fruits.filter(f=>!f.done);}
 else{const r=[42,34,27][difficulty];pads=pads.map((p,i)=>{const x=clamp(500+inputs[i].x*250,210+r,790-r),y=i===0?clamp(520+inputs[i].y*130,350+r,670-r):clamp(180-inputs[i].y*130,30+r,350-r);const dx=x-p.x,dy=y-p.y,v=Math.hypot(dx,dy),s=Math.min(1,850*dt/(v||1));return {x:p.x+dx*s,y:p.y+dy*s,vx:dx*s/dt,vy:dy*s/dt};});if(serve>0){serve-=dt;return;}const goal=hockeyStep(puck,pads,r,dt,[450,650,850][difficulty]);if(goal){score[goal-1]++;puck={x:500,y:350,vx:70,vy:goal===1?-230:230};serve=2;beep(850);}}
}
function circle(x:number,y:number,r:number,color:string){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function text(s:string,x:number,y:number,size=28,color='#493327'){ctx.fillStyle=color;ctx.font=`bold ${size}px sans-serif`;ctx.textAlign='center';ctx.fillText(s,x,y);}
function drawFruit(f:Fruit){ctx.save();ctx.translate(f.x,f.y);circle(0,0,f.r,['#8e4e28','#b7c654','#ec862c'][f.kind]);if(f.kind===0){ctx.fillStyle='#dcb283';ctx.beginPath();ctx.ellipse(0,9,15,7,0,0,Math.PI*2);ctx.fill();}if(f.kind===1)circle(0,-10,12,'#b7c654');ctx.strokeStyle='#675036';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(3,-25);ctx.stroke();ctx.fillStyle='#52793d';ctx.beginPath();ctx.ellipse(8,-18,9,4,-.4,0,Math.PI*2);ctx.fill();ctx.restore();}
function draw(){ctx.clearRect(0,0,1000,700);ctx.fillStyle=game==='harvest'?'#fff1d2':'#e4f4ff';ctx.fillRect(0,0,1000,700);text(`残り ${Math.ceil(remaining)} 秒`,820,45);if(game==='harvest'){text(`収穫 ${score[0]} 点`,170,45);const b=board(inputs[0],inputs[1],[430,350,280][difficulty],maxAngle*Math.PI/180);ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.angle);ctx.fillStyle='#9c643a';ctx.fillRect(-b.length/2,-1,b.length,18);ctx.fillStyle='#d5a061';ctx.fillRect(-b.length/2,0,b.length,5);ctx.restore();text('🤲',b.left.x,b.left.y+35,38);text('🤲',b.right.x,b.right.y+35,38);for(const f of fruits){drawFruit(f);if(f.caught){ctx.fillStyle='#57924b';ctx.fillRect(f.x-20,f.y-32,40*f.held,5);}}text('P1',b.left.x,b.left.y+65,20);text('P2',b.right.x,b.right.y+65,20);}
 else{ctx.strokeStyle='#337390';ctx.lineWidth=6;ctx.strokeRect(210,30,580,640);ctx.beginPath();ctx.moveTo(210,350);ctx.lineTo(790,350);ctx.stroke();ctx.strokeStyle='#e4f4ff';ctx.lineWidth=10;for(const y of [30,670]){ctx.beginPath();ctx.moveTo(410,y);ctx.lineTo(590,y);ctx.stroke();}for(let i=0;i<2;i++){circle(pads[i].x,pads[i].y,[42,34,27][difficulty],i===0?'#d94e4e':'#367bc6');text(`P${i+1}`,pads[i].x,pads[i].y+8,22,'white');}circle(puck.x,puck.y,12,'#253844');text(`P1 ${score[0]}  —  ${score[1]} P2`,500,25,24);if(serve>0)text(String(Math.ceil(serve)),500,350,70);}
 if(state==='countdown'||state==='paused'||state==='ended'){ctx.fillStyle='#fffdf0cc';ctx.fillRect(200,250,600,150);text(state==='countdown'?String(Math.ceil(count)):state==='paused'?'ひとやすみ':'ゲーム終了！',500,340,60);}}
if(host&&(slot===0||slot===1))controller();else setupHost();
